
import java.util.ArrayList;
import java.util.InputMismatchException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kerem
 */
public class AnaEkran extends javax.swing.JFrame {
    private personelİslemleri personel_islemleri=new personelİslemleri();
    private girisİslemleri giris_islemleri=new girisİslemleri();
    /**
     * Creates new form AnaEkran
     */
    public AnaEkran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        solpanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        sagpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ad_alanı = new javax.swing.JTextField();
        parola_alanı = new javax.swing.JPasswordField();
        giris = new javax.swing.JButton();
        kaydol = new javax.swing.JButton();
        personel_girisi = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        mesaj_alanı = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("araba otomasyonu");
        setBounds(new java.awt.Rectangle(500, 150, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        solpanel.setBackground(new java.awt.Color(97, 212, 195));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/solpanel3.jpg"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Colonna MT", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Duman Oto Kiralama");

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout solpanelLayout = new javax.swing.GroupLayout(solpanel);
        solpanel.setLayout(solpanelLayout);
        solpanelLayout.setHorizontalGroup(
            solpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(solpanelLayout.createSequentialGroup()
                .addGroup(solpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(solpanelLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel3))
                    .addGroup(solpanelLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, solpanelLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(solpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(41, 41, 41))
        );
        solpanelLayout.setVerticalGroup(
            solpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(solpanelLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(58, 58, 58)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        getContentPane().add(solpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 630));

        sagpanel.setBackground(new java.awt.Color(36, 47, 65));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kullanıcı  Adı :");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Parola :");

        ad_alanı.setBackground(new java.awt.Color(36, 47, 65));
        ad_alanı.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        ad_alanı.setForeground(new java.awt.Color(255, 255, 255));
        ad_alanı.setBorder(null);

        parola_alanı.setBackground(new java.awt.Color(36, 47, 65));
        parola_alanı.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        parola_alanı.setForeground(new java.awt.Color(255, 255, 255));
        parola_alanı.setBorder(null);

        giris.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        giris.setForeground(new java.awt.Color(36, 47, 65));
        giris.setText("Giriş");
        giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                girisActionPerformed(evt);
            }
        });

        kaydol.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        kaydol.setForeground(new java.awt.Color(36, 47, 65));
        kaydol.setText("Kaydol");
        kaydol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaydolActionPerformed(evt);
            }
        });

        personel_girisi.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        personel_girisi.setForeground(new java.awt.Color(36, 47, 65));
        personel_girisi.setText("Personel Girişi");
        personel_girisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personel_girisiActionPerformed(evt);
            }
        });

        mesaj_alanı.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        mesaj_alanı.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout sagpanelLayout = new javax.swing.GroupLayout(sagpanel);
        sagpanel.setLayout(sagpanelLayout);
        sagpanelLayout.setHorizontalGroup(
            sagpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sagpanelLayout.createSequentialGroup()
                .addGroup(sagpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sagpanelLayout.createSequentialGroup()
                        .addGroup(sagpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sagpanelLayout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addGroup(sagpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(sagpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(sagpanelLayout.createSequentialGroup()
                                            .addComponent(giris, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(51, 51, 51)
                                            .addComponent(kaydol, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(sagpanelLayout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(personel_girisi, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(sagpanelLayout.createSequentialGroup()
                                        .addGap(106, 106, 106)
                                        .addComponent(ad_alanı, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(sagpanelLayout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addGroup(sagpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(sagpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(parola_alanı, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 102, Short.MAX_VALUE))
                    .addGroup(sagpanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(mesaj_alanı, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        sagpanelLayout.setVerticalGroup(
            sagpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sagpanelLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(sagpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ad_alanı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(sagpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parola_alanı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(sagpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(giris, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kaydol, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(personel_girisi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(mesaj_alanı, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );

        getContentPane().add(sagpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 500, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kaydolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaydolActionPerformed
        kayıtEkranı kayıt=new kayıtEkranı(this, true);
        kayıt.setVisible(true);
    }//GEN-LAST:event_kaydolActionPerformed

    private void girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_girisActionPerformed
        mesaj_alanı.setText("");
        
        String ad=ad_alanı.getText();
       String parola=String.valueOf(parola_alanı.getPassword());
       
        
        boolean giris=giris_islemleri.giris_yap(ad,parola);
        if(ad.trim().equals("")&& parola.trim().equals("")){
            mesaj_alanı.setText("lütfen boslukları doldurun");
        
        }
       
        else {
          
       String ad1=ad_alanı.getText();
       String parola1=String.valueOf(parola_alanı.getPassword());
        if(giris){
        kullanıcıEkranı kullanıcıEkranı=new kullanıcıEkranı();
            setVisible(false);
            kullanıcıEkranı.setVisible(true);
        
        }
        else{
        mesaj_alanı.setText("boyle bir kullanıcı yok.lütfen once kaydolun...!");
        
        }
        
        
        }
        
       
        
    }//GEN-LAST:event_girisActionPerformed
    
    private void personel_girisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personel_girisiActionPerformed
        personelGirisEkranı giris_ekranı=new personelGirisEkranı(this, true);
        giris_ekranı.setVisible(true);
        
        
        
    }//GEN-LAST:event_personel_girisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaEkran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad_alanı;
    private javax.swing.JButton giris;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JButton kaydol;
    private javax.swing.JLabel mesaj_alanı;
    private javax.swing.JPasswordField parola_alanı;
    private javax.swing.JButton personel_girisi;
    private javax.swing.JPanel sagpanel;
    private javax.swing.JPanel solpanel;
    // End of variables declaration//GEN-END:variables
}
