
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kerem
 */
public class kullanıcıEkranı extends javax.swing.JFrame {
    girisİslemleri giris_islemleri=new girisİslemleri();

    /**
     * Creates new form kullanıcıEkranı
     */
    public kullanıcıEkranı() {
        initComponents();
        arabaları_getir();
    }
    public void arabaları_getir(){
        DefaultTableModel model=(DefaultTableModel)tablo_alanı.getModel();
        ArrayList<personel> tablo_array=new ArrayList<personel>();
        tablo_array=giris_islemleri.arabaları_goruntule();
        if(tablo_array!=null){
            for(personel arabacıktısı:tablo_array){
                Object[]eklenecekler={arabacıktısı.getId(),arabacıktısı.getMarka(),arabacıktısı.getModel(),arabacıktısı.getFiyat()};
                model.addRow(eklenecekler);
            }
            
        }
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablo_alanı = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        marka_alanı = new javax.swing.JTextField();
        model_alanı = new javax.swing.JTextField();
        fiyat_alano = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ad_alanı = new javax.swing.JTextField();
        soyad_alanı = new javax.swing.JTextField();
        tc_alanı = new javax.swing.JTextField();
        günsayısı_alanı = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        toplam_fiyat = new javax.swing.JButton();
        toplam_fiyat_alanı = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        mesaj_alanı = new javax.swing.JLabel();
        kirala = new javax.swing.JButton();
        cıkıs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(600, 150, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        tablo_alanı.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "marka", "model", "fiyat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablo_alanı.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablo_alanıMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablo_alanı);
        if (tablo_alanı.getColumnModel().getColumnCount() > 0) {
            tablo_alanı.getColumnModel().getColumn(0).setResizable(false);
            tablo_alanı.getColumnModel().getColumn(1).setResizable(false);
            tablo_alanı.getColumnModel().getColumn(2).setResizable(false);
            tablo_alanı.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("marka  :");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("model  :");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("fiyat :");

        marka_alanı.setEditable(false);
        marka_alanı.setBackground(new java.awt.Color(0, 102, 102));
        marka_alanı.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        marka_alanı.setForeground(new java.awt.Color(255, 255, 255));
        marka_alanı.setBorder(null);

        model_alanı.setEditable(false);
        model_alanı.setBackground(new java.awt.Color(0, 102, 102));
        model_alanı.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        model_alanı.setForeground(new java.awt.Color(255, 255, 255));
        model_alanı.setBorder(null);
        model_alanı.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                model_alanıActionPerformed(evt);
            }
        });

        fiyat_alano.setEditable(false);
        fiyat_alano.setBackground(new java.awt.Color(0, 102, 102));
        fiyat_alano.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        fiyat_alano.setForeground(new java.awt.Color(255, 255, 255));
        fiyat_alano.setBorder(null);
        fiyat_alano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiyat_alanoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ad :");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("soyad :");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tc :");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Kiralanacak gün sayısı :");

        ad_alanı.setBackground(new java.awt.Color(0, 102, 102));
        ad_alanı.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ad_alanı.setForeground(new java.awt.Color(255, 255, 255));
        ad_alanı.setBorder(null);

        soyad_alanı.setBackground(new java.awt.Color(0, 102, 102));
        soyad_alanı.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        soyad_alanı.setForeground(new java.awt.Color(255, 255, 255));
        soyad_alanı.setBorder(null);

        tc_alanı.setBackground(new java.awt.Color(0, 102, 102));
        tc_alanı.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        tc_alanı.setForeground(new java.awt.Color(255, 255, 255));
        tc_alanı.setBorder(null);

        günsayısı_alanı.setBackground(new java.awt.Color(0, 102, 102));
        günsayısı_alanı.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        günsayısı_alanı.setForeground(new java.awt.Color(255, 255, 255));
        günsayısı_alanı.setBorder(null);

        toplam_fiyat.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        toplam_fiyat.setForeground(new java.awt.Color(0, 102, 102));
        toplam_fiyat.setText("Toplam Fiyat");
        toplam_fiyat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toplam_fiyatActionPerformed(evt);
            }
        });

        toplam_fiyat_alanı.setEditable(false);
        toplam_fiyat_alanı.setBackground(new java.awt.Color(0, 102, 102));
        toplam_fiyat_alanı.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        toplam_fiyat_alanı.setForeground(new java.awt.Color(255, 255, 255));
        toplam_fiyat_alanı.setBorder(null);

        mesaj_alanı.setForeground(new java.awt.Color(255, 255, 255));

        kirala.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        kirala.setForeground(new java.awt.Color(0, 102, 102));
        kirala.setText("Kirala");
        kirala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kiralaActionPerformed(evt);
            }
        });

        cıkıs.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        cıkıs.setForeground(new java.awt.Color(0, 102, 102));
        cıkıs.setText("Çıkış");
        cıkıs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cıkısActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ad_alanı, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                .addComponent(soyad_alanı))
                            .addComponent(günsayısı_alanı, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tc_alanı, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(190, Short.MAX_VALUE)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addComponent(fiyat_alano, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(marka_alanı, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(59, 59, 59)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(model_alanı, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(mesaj_alanı, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(toplam_fiyat, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator11)
                            .addComponent(toplam_fiyat_alanı, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(kirala, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cıkıs, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ad_alanı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(marka_alanı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(soyad_alanı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tc_alanı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(model_alanı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(fiyat_alano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(günsayısı_alanı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mesaj_alanı, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(toplam_fiyat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toplam_fiyat_alanı, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kirala)
                    .addComponent(cıkıs))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fiyat_alanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiyat_alanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fiyat_alanoActionPerformed

    private void model_alanıActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_model_alanıActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_model_alanıActionPerformed

    private void tablo_alanıMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablo_alanıMouseClicked
        DefaultTableModel model=(DefaultTableModel)tablo_alanı.getModel();
        
        int secilirow=tablo_alanı.getSelectedRow();
        marka_alanı.setText(model.getValueAt(secilirow, 1).toString());
        model_alanı.setText(model.getValueAt(secilirow, 2).toString());
        fiyat_alano.setText(model.getValueAt(secilirow, 3).toString());
        
        
    }//GEN-LAST:event_tablo_alanıMouseClicked

    private void toplam_fiyatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toplam_fiyatActionPerformed
        DefaultTableModel model=(DefaultTableModel)tablo_alanı.getModel();
        int seciliRow=tablo_alanı.getSelectedRow();
        mesaj_alanı.setText("");
        String ad=ad_alanı.getText();
        String soyad=soyad_alanı.getText();
        String tc=tc_alanı.getText();
        String günsayısı1=günsayısı_alanı.getText();
        if(ad.trim().equals("")&& soyad.trim().equals("")&&tc.trim().equals("")){
            mesaj_alanı.setText("lütfen boslukları doldurun");
            
        }
        else if(günsayısı1.trim().equals("")){
        mesaj_alanı.setText("lütfen tüm boslukları doldurunuz");
        }
        else if(seciliRow==-1){
            if(model.getRowCount()==0){
            mesaj_alanı.setText("kiralanacak arac tablosu suan bos");
            }
            else{
            JOptionPane.showMessageDialog(this, "lütfen kiralanacak aracı tablodan secin");
            }
        
        }
        else {
        int günsayısı=Integer.parseInt(günsayısı_alanı.getText());
        int fiyat=Integer.parseInt(fiyat_alano.getText());
        int toplam=günsayısı*fiyat;
        String toplamlarsonucu=String.valueOf(toplam);
        toplam_fiyat_alanı.setText(toplamlarsonucu+" TL");
               
        }
    }//GEN-LAST:event_toplam_fiyatActionPerformed

    private void kiralaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kiralaActionPerformed
        DefaultTableModel model=(DefaultTableModel)tablo_alanı.getModel();
        mesaj_alanı.setText("");
        String ad=ad_alanı.getText();
        String soyad=soyad_alanı.getText();
        String tc=tc_alanı.getText();
        String günsayısı1=günsayısı_alanı.getText();
        int secilirow=tablo_alanı.getSelectedRow();

        if(ad.trim().equals("")&& soyad.trim().equals("")&&tc.trim().equals("")){
            mesaj_alanı.setText("lütfen boslukları doldurun");
            
        }
        else if(günsayısı1.trim().equals("")){
        mesaj_alanı.setText("lütfen tüm boslukları doldurunuz");
        }
        else if(toplam_fiyat_alanı.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "lütfen toplam fiyatı Ögrenin");
        
        }
        else if(secilirow==-1){
              
            if(model.getRowCount()==0){
                mesaj_alanı.setText("tablonuz suan bos");
            }
            else{
            JOptionPane.showMessageDialog(this, "lütfen kiralanacak aracı tablodan seçin");
            }
        
        }
        else{
        JOptionPane.showMessageDialog(this, "Talebeniz alınmıstır.lütfen ücreti ile birlikte dükkana ugrayınız..");
        
        }
    }//GEN-LAST:event_kiralaActionPerformed

    private void cıkısActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cıkısActionPerformed
        System.exit(0);
               
                
    }//GEN-LAST:event_cıkısActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kullanıcıEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kullanıcıEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kullanıcıEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kullanıcıEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kullanıcıEkranı().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad_alanı;
    private javax.swing.JButton cıkıs;
    private javax.swing.JTextField fiyat_alano;
    private javax.swing.JTextField günsayısı_alanı;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JButton kirala;
    private javax.swing.JTextField marka_alanı;
    private javax.swing.JLabel mesaj_alanı;
    private javax.swing.JTextField model_alanı;
    private javax.swing.JTextField soyad_alanı;
    private javax.swing.JTable tablo_alanı;
    private javax.swing.JTextField tc_alanı;
    private javax.swing.JButton toplam_fiyat;
    private javax.swing.JTextField toplam_fiyat_alanı;
    // End of variables declaration//GEN-END:variables
}
