
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kerem
 */
public class personelEkranı extends javax.swing.JFrame {
    private  personelİslemleri personelislemleri=new personelİslemleri();

    /**
     * Creates new form personelEkranı
     */
    public personelEkranı() {
        initComponents();
        arabaları_getir();
    }
    
    public void arabaları_getir(){
        ArrayList<personel> personel_array=new ArrayList<personel>();
        DefaultTableModel model=(DefaultTableModel)tablo_alanı.getModel();
        model.setRowCount(0);
        personel_array=personelislemleri.arabaları_getir();
        if(personel_array!=null){
           for(personel personel:personel_array){
             
               Object [] eklenecekler={personel.getId(),personel.getMarka(),personel.getModel(),personel.getFiyat()};
               model.addRow(eklenecekler);
           
           }
           
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablo_alanı = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        marka_alanı = new javax.swing.JTextField();
        model_alanı = new javax.swing.JTextField();
        fiyat_alanı = new javax.swing.JTextField();
        ekle = new javax.swing.JButton();
        sil = new javax.swing.JButton();
        guncelle = new javax.swing.JButton();
        cıkıs = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        mesaj_alanı = new javax.swing.JLabel();
        goster = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(500, 150, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(36, 47, 65));

        tablo_alanı.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "marka", "model", "fiyat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablo_alanı.setGridColor(new java.awt.Color(204, 204, 204));
        tablo_alanı.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablo_alanıMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablo_alanı);
        if (tablo_alanı.getColumnModel().getColumnCount() > 0) {
            tablo_alanı.getColumnModel().getColumn(0).setResizable(false);
            tablo_alanı.getColumnModel().getColumn(1).setResizable(false);
            tablo_alanı.getColumnModel().getColumn(2).setResizable(false);
            tablo_alanı.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("marka :");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("model :");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("fiyat :");

        marka_alanı.setBackground(new java.awt.Color(0, 102, 102));
        marka_alanı.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        marka_alanı.setForeground(new java.awt.Color(255, 255, 255));
        marka_alanı.setBorder(null);

        model_alanı.setBackground(new java.awt.Color(0, 102, 102));
        model_alanı.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        model_alanı.setForeground(new java.awt.Color(255, 255, 255));
        model_alanı.setBorder(null);

        fiyat_alanı.setBackground(new java.awt.Color(0, 102, 102));
        fiyat_alanı.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        fiyat_alanı.setForeground(new java.awt.Color(255, 255, 255));
        fiyat_alanı.setBorder(null);

        ekle.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        ekle.setForeground(new java.awt.Color(0, 102, 102));
        ekle.setText("Arac Ekle");
        ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleActionPerformed(evt);
            }
        });

        sil.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        sil.setForeground(new java.awt.Color(0, 102, 102));
        sil.setText("Arac Sil");
        sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silActionPerformed(evt);
            }
        });

        guncelle.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        guncelle.setForeground(new java.awt.Color(0, 102, 102));
        guncelle.setText("Arac Güncelle");
        guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelleActionPerformed(evt);
            }
        });

        cıkıs.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        cıkıs.setForeground(new java.awt.Color(0, 102, 102));
        cıkıs.setText("cıkıs");
        cıkıs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cıkısActionPerformed(evt);
            }
        });

        mesaj_alanı.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        mesaj_alanı.setForeground(new java.awt.Color(255, 255, 255));

        goster.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        goster.setForeground(new java.awt.Color(0, 102, 102));
        goster.setText("Kişileri Göster");
        goster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gosterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator3))))
                .addContainerGap(134, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(marka_alanı, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(fiyat_alanı, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(model_alanı, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(mesaj_alanı, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(goster, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(cıkıs, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(ekle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guncelle, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(sil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(103, 103, 103))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marka_alanı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(model_alanı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(fiyat_alanı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sil, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(mesaj_alanı, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(goster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(cıkıs, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleActionPerformed
    mesaj_alanı.setText("");
    String marka=marka_alanı.getText();
    String model=model_alanı.getText();
    String fiyat=fiyat_alanı.getText();
    if(marka.trim().equals("")){
    mesaj_alanı.setText("lütfen marka alanı doldurunuz");
    
    }
    else if(model.trim().equals("")){
        mesaj_alanı.setText("lütfen model alanını bos bırakmayınız");
        
    }
    else if(fiyat.trim().equals("")){
    mesaj_alanı.setText("fiyat alanı bos bırakılamaz");
    }
    else{
    
    personelislemleri.ekle(marka,model,fiyat);
    mesaj_alanı.setText("ekleme basarılı");
    arabaları_getir();
   
    }
        
    }//GEN-LAST:event_ekleActionPerformed

    private void tablo_alanıMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablo_alanıMouseClicked
        DefaultTableModel model=(DefaultTableModel)tablo_alanı.getModel();
        int secilirow=tablo_alanı.getSelectedRow();
        marka_alanı.setText(model.getValueAt(secilirow, 1).toString());
        model_alanı.setText(model.getValueAt(secilirow, 2).toString());
        fiyat_alanı.setText(model.getValueAt(secilirow, 3).toString());
        
    }//GEN-LAST:event_tablo_alanıMouseClicked

    private void silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silActionPerformed
        mesaj_alanı.setText("");
        DefaultTableModel model=(DefaultTableModel)tablo_alanı.getModel();
        int secilirow=tablo_alanı.getSelectedRow();
       if(secilirow==-1){
           if(model.getRowCount()==0){
               mesaj_alanı.setText("tablonuz suan bos");
           
           }
           else{
           mesaj_alanı.setText("lütfen silinecek satırı seçin");
           }
       }
       else{
       int id=(int)model.getValueAt(secilirow, 0);
       personelislemleri.sil(id);
       mesaj_alanı.setText("silme basarılı");
       arabaları_getir();
       
       }
       
        
    }//GEN-LAST:event_silActionPerformed

    private void guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelleActionPerformed
      DefaultTableModel model1=(DefaultTableModel)tablo_alanı.getModel();
      mesaj_alanı.setText("");
      int secilirow=tablo_alanı.getSelectedRow();
      String marka=marka_alanı.getText();
      String model=model_alanı.getText();
      String fiyat=fiyat_alanı.getText();
    
      if(secilirow==-1){
          if(model1.getRowCount()==0){
          mesaj_alanı.setText("tablonuz suan bos");
          }
          else{
          mesaj_alanı.setText("lütfen güncellenecek satırı secin");
          }
      
      
      }
      else {
      int id=(int)model1.getValueAt(secilirow, 0);
      personelislemleri.güncelle(id,marka,model,fiyat);
      mesaj_alanı.setText("guncelleme basarılı");
      arabaları_getir();
      marka_alanı.setText("");
      model_alanı.setText("");
      fiyat_alanı.setText("");
      }
      
        
    }//GEN-LAST:event_guncelleActionPerformed

    private void cıkısActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cıkısActionPerformed
       
        System.exit(0);
       
    }//GEN-LAST:event_cıkısActionPerformed

    private void gosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gosterActionPerformed
       kullanıcıları_goster goster=new kullanıcıları_goster(this, true);
       goster.setVisible(true);
    }//GEN-LAST:event_gosterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(personelEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(personelEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(personelEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(personelEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new personelEkranı().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cıkıs;
    private javax.swing.JButton ekle;
    private javax.swing.JTextField fiyat_alanı;
    private javax.swing.JButton goster;
    private javax.swing.JButton guncelle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField marka_alanı;
    private javax.swing.JLabel mesaj_alanı;
    private javax.swing.JTextField model_alanı;
    private javax.swing.JButton sil;
    private javax.swing.JTable tablo_alanı;
    // End of variables declaration//GEN-END:variables
}
